server:
  port: 8086

spring:
  application:
    name: websocket-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: websocket-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pulseops.shared.event"

pulseops:
  jwt:
    secret: pulseopsSecretKeyPulseOpsSecretKeyPulseOpsSecretKey
